# Session 16

[![Open and Execute in Google Colaboratory](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/astrojuanlu/ie-mbd-python-data-analysis-i/blob/main/sessions/Session%2016.ipynb)

- Typical loop constructs
- Using flow control to create and update data structures and solving questions

## Typical loop constructs

### Initializing and accumulating

Very often you will need to create a list of elements after doing some processing. A typical way of doing that is as follows:

In [1]:
initial_list = []  # Initialize the list as empty
for number in range(10):  # Iterate over some container
    next_item = number ** 2  # Assign the next item
    initial_list.append(next_item)  # Accumulate the next item in the list

initial_list

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Notice that this is very similar to how list comprehensions work:

In [2]:
[number ** 2 for number in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### Iterating with indexes with `enumerate`

When iterating over a sequence, we can extract simultaneously a numerical index and the values themselves, using `enumerate`:

In [3]:
for letter in "abcd":
    print(letter)

a
b
c
d

In [4]:
for index, letter in enumerate("abcd"):
    print(index, "-->", letter)

0 --> a
1 --> b
2 --> c
3 --> d

## Exercises

### 1. Split and concat with loops

Using the Rick & Morty data, split the data if five datasets, one per season.

For that, accumulate the five DataFrames in a list, called `list_df_seasons`.

To verify that it worked, pass it directly to `pd.concat` and check that the assembled dataframe and the original one are the same.

You can also repeat the exercise with a list comprehension.

In [5]:
RICK_MORTY_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/rick-and-morty.json"
)

In [6]:
import pandas as pd
import requests

data = requests.get(RICK_MORTY_DATA_URL).json()
df = pd.DataFrame.from_records(data["_embedded"]["episodes"])

In [7]:
df.head(2)

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,rating,image,summary,_links
0,14308,https://www.tvmaze.com/episodes/14308/rick-and...,Pilot,1,1,regular,2013-12-02,22:30,2013-12-03T03:30:00+00:00,30,{'average': 8.6},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick takes Morty to another dimension to ge...,{'self': {'href': 'https://api.tvmaze.com/epis...
1,14309,https://www.tvmaze.com/episodes/14309/rick-and...,Lawnmower Dog,1,2,regular,2013-12-09,22:30,2013-12-10T03:30:00+00:00,30,{'average': 8.9},{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Morty's small, white dog Snuffles gets on t...",{'self': {'href': 'https://api.tvmaze.com/epis...

In [20]:
df_season_1 = df.loc[df["season"]==1]
df_season_2 = df.loc[df["season"]==2]
df_season_3 = df.loc[df["season"]==3]
df_season_4 = df.loc[df["season"]==4]
df_season_5 = df.loc[df["season"]==5]

In [21]:
df_season_1.head(5)

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,rating,image,summary,_links
0,14308,https://www.tvmaze.com/episodes/14308/rick-and...,Pilot,1,1,regular,2013-12-02,22:30,2013-12-03T03:30:00+00:00,30,{'average': 8.6},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick takes Morty to another dimension to ge...,{'self': {'href': 'https://api.tvmaze.com/epis...
1,14309,https://www.tvmaze.com/episodes/14309/rick-and...,Lawnmower Dog,1,2,regular,2013-12-09,22:30,2013-12-10T03:30:00+00:00,30,{'average': 8.9},{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Morty's small, white dog Snuffles gets on t...",{'self': {'href': 'https://api.tvmaze.com/epis...
2,14310,https://www.tvmaze.com/episodes/14310/rick-and...,Anatomy Park,1,3,regular,2013-12-16,22:30,2013-12-17T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>It's around Christmas time and Jerry's pare...,{'self': {'href': 'https://api.tvmaze.com/epis...
3,14311,https://www.tvmaze.com/episodes/14311/rick-and...,M. Night Shaym-Aliens!,1,4,regular,2014-01-13,22:30,2014-01-14T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick and Morty try to get to the bottom of ...,{'self': {'href': 'https://api.tvmaze.com/epis...
4,14312,https://www.tvmaze.com/episodes/14312/rick-and...,Meeseeks and Destroy,1,5,regular,2014-01-20,22:30,2014-01-21T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick provides the family with a solution to...,{'self': {'href': 'https://api.tvmaze.com/epis...

In [22]:
list_Df_seasons = []
for season in range(df["season"].min(),df["season"].max() + 1):
  list_Df_seasons.append(df.loc[df["season"]== season])

In [24]:
pd.concat(list_Df_seasons).equals(df)

True

## Using flow control (Practice)

### 2. Tenders data

Read this JSON data and answer some questions.

In [25]:
TENDERS_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/tenders.es.json"
)

In [26]:
data_t = requests.get(TENDERS_DATA_URL).json()

In [30]:
df_t = pd.DataFrame.from_records(data_t["data"])

In [31]:
df_t.head(5)

,id,date,deadline_date,deadline_length_days,title,category,sid,src_url,purchaser,type,awarded
0,831333,2021-06-29,2021-06-07,22,Servicio de producción de células mesenquimale...,services,7791427,https://contrataciondelestado.es/wps/poc?uri=d...,"{'id': '1988', 'sid': None, 'name': None}","{'id': 'negotiated-without-publicity', 'name':...","[{'date': '2021-06-29', 'value_for_two': 16356..."
1,831322,2021-05-17,2021-06-01,15,Contratación de Servicio de la Programación de...,services,7554969,https://contrataciondelestado.es/wps/poc?uri=d...,"{'id': '49', 'sid': None, 'name': None}","{'id': 'simplified-open', 'name': 'Simplified ...","[{'date': '2021-06-29', 'value_for_two': 0, 's..."
2,831319,2021-06-29,NaN,NaN,Adquisicion de impresoras A4 Color para el Min...,supplies,7791419,https://contrataciondelestado.es/wps/poc?uri=d...,"{'id': '1952', 'sid': None, 'name': None}",{'id': 'contract-based-on-a-framework-agreemen...,"[{'date': '2021-06-29', 'value_for_two': 0, 's..."
3,831318,2021-06-29,NaN,NaN,Renovación de las licencias de productos Opent...,supplies,7791418,https://contrataciondelestado.es/wps/poc?uri=d...,"{'id': '1952', 'sid': None, 'name': None}",{'id': 'contract-based-on-a-framework-agreemen...,"[{'date': '2021-06-29', 'value_for_two': 48916..."
4,831317,2021-05-26,2021-06-11,16,Servicios de digitalización de las solicitudes...,services,7611066,https://contrataciondelestado.es/wps/poc?uri=d...,"{'id': '281', 'sid': None, 'name': None}","{'id': 'open', 'name': 'Open', 'slug': 'open'}","[{'date': '2021-06-29', 'value_for_two': 19781..."

First, you will need to inspect the data structure and locate the actual elements inside of it (similar to the Rick & Morty data).

For every question, try to do it with and without pandas DataFrames. Compare both approaches in terms of readability and ease of implementation.

1. Looks like the `category` property has low cardinality. How many distinct categories are there?

In [ ]:
# hint:

# categories_set = set()
# for tender in data[...]:
#   categories_set...
#
# print(len(categories_set))

In [34]:
df_t["category"].nunique()

4

In [50]:
categories_set = set()

list_c = [data_t["data"][i]["category"] for i in range(len(data_t["data"]))]
set_c = set(list_c)
print(set_c)
print(len(set_c))

#for tender in data_t["data_t"][0]["category"]

{'supplies', 'services', 'other', 'constructions'}
4

In [45]:
len(data_t["data"])

100

In [42]:
data_t["data"][5]["category"]

'supplies'

2. What is the average deadline length in days, excluding the missing data?

In [ ]:
# hint:

# from statistics import ...

# deadlines = ...
# for tender in ...
#     if "deadline_length_days" in tender:
#         deadlines...
#
# mean(deadlines)  # 22.2222

In [61]:
pd.to_numeric(df_t.loc[:,"deadline_length_days"].dropna()).mean()

np.float64(22.22222222222222)

In [66]:
list_d = [data_t["data"][i]["deadline_length_days"] for i in range(len(data_t["data"]))]

KeyError: 'deadline_length_days'

In [64]:
data_t["data"][0]["deadline_length_days"]

'22'

3. How many tenders are there of each category?

In [ ]:
# hint:

# category_counts = {}
# for category in categories_set:
#   category_counts[...] = 0
#
# for tender in ...:
#   category_counts[...] += 1
#
# print(category_counts)  # {'other': 8, 'constructions': 11, ...

4. How many tenders are there of each "type"?

In [ ]:
# tender_types = ...
# for tender in ...
#     tender_t = tender["type"]...
#     if tender_t in tender_types:
#         tender_types[tender_t] += 1
#     else:
#         ...
#
# tender_types  # {'negotiated-without-publicity': 10, 'simplified-open': ...

5. In how many cases the "awarded date" is not the same as the "date" field?

In [ ]:
# hint:

# tender_dates = []
# for tender in ...:
#     tender_dates.append({
#         "date": tender["date"],
#         "awarded_date": ...
#     })
#
# for tender_info in ...:
#     tender_info["dates_equal"] = ...
#
# tender_date_counts = {False: 0, True: 0}
# for tender_info in tender_dates:
#     ...
#
# print(tender_date_counts)  # {False: 72, True: 28}