# Session 12

[![Open and Execute in Google Colaboratory](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/astrojuanlu/ie-mbd-python-data-analysis-i/blob/main/sessions/Session%2012.ipynb)

- The index in pandas
- `.loc` vs `.iloc`
- Merge & Join
- Dealing with missing data

## The index in pandas

> There is just one core concept that brings together almost all of the pandas API [...]: the index and index alignment.

James Powell ([source](https://youtu.be/pjq3QOxl9Ok?si=B-wOGZJ7XvO70zmk))

The index is a property of pandas DataFrames that allows you to refer to specific rows by _label_, rather than by _position_. You have already used it, but there is so much that can be done with it.

In [ ]:
import pandas as pd

df_covid = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/"
    "data/national_covid19.csv"
)
df_covid.head()

,date,cases_total,cases_pcr,cases_test_ab,discharges,deceases,icu,hospitalized
0,2020-02-21,3.0,3,NaN,NaN,NaN,NaN,NaN
1,2020-02-22,3.0,3,NaN,NaN,NaN,NaN,NaN
2,2020-02-23,3.0,3,NaN,NaN,NaN,NaN,NaN
3,2020-02-24,3.0,3,NaN,NaN,NaN,NaN,NaN
4,2020-02-25,4.0,4,NaN,NaN,NaN,NaN,NaN

You can visually distinguish the index on the left hand side because the values are highlighted in bold. By default, an autoincrement, integer index is used, like in this case.

Remember that you can use `.loc` to index and slice a DataFrame by label:

In [ ]:
df_covid.loc[0:3]

,date,cases_total,cases_pcr,cases_test_ab,discharges,deceases,icu,hospitalized
0,2020-02-21,3.0,3,NaN,NaN,NaN,NaN,NaN
1,2020-02-22,3.0,3,NaN,NaN,NaN,NaN,NaN
2,2020-02-23,3.0,3,NaN,NaN,NaN,NaN,NaN
3,2020-02-24,3.0,3,NaN,NaN,NaN,NaN,NaN

However, things start to get interesting when you use some other column as an index. In this case, let's use the date:

In [ ]:
df_covid["date"].is_unique  # Good sanity check, not mandatory

True

In [ ]:
df_covid_r = df_covid.set_index("date")
df_covid_r.head()

,cases_total,cases_pcr,cases_test_ab,discharges,deceases,icu,hospitalized
date,,,,,,,
2020-02-21,3.0,3,NaN,NaN,NaN,NaN,NaN
2020-02-22,3.0,3,NaN,NaN,NaN,NaN,NaN
2020-02-23,3.0,3,NaN,NaN,NaN,NaN,NaN
2020-02-24,3.0,3,NaN,NaN,NaN,NaN,NaN
2020-02-25,4.0,4,NaN,NaN,NaN,NaN,NaN

Notice that `date` is no longer a column!

In [ ]:
df_covid_r["date"]  # Fails

But more importantly, now you can use the date as the index:

In [ ]:
df_covid_r.loc["2020-04-01":"2020-04-05"]

## `.loc` vs `.iloc`

Now, `.loc` is very powerful because it allows you to use labels, rather than positions. But what if you want positions for some reason?

Well, that's what `.iloc` is for:

In [ ]:
df_covid_r.iloc[:3]

Notice that `.iloc` follows the Python semantics of slicing (the end is not included), unlike `.loc`:

In [ ]:
df_covid.loc[:3]

## Exercises

### 1. Wildfires in Spain

Read the `data/fires-all.csv` file into a pandas DataFrame.

How many fires were there in the year 2018? Compute that in 2 ways:
- Filtering on the `fecha` column
- Setting `fecha` as the index

Verify that the result is exactly the same.

In [ ]:
FIRES_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/"
    "data/fires-subset.csv"
)
FIRES_URL

'https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/fires-subset.csv'

In [ ]:
df_wildfire = pd.read_csv(FIRES_URL)
df_wildfire.head()

,id,superficie,fecha,lat,lng,latlng_explicit,idcomunidad,idprovincia,idmunicipio,municipio,...,causa_supuesta,causa_desc,muertos,heridos,time_ctrl,time_ext,personal,medios,gastos,perdidas
0,2015030001,2.50,2015-01-01,38.854954,-0.129543,1.0,9,3,102,PEGO,...,0,12,0,0,153,364,28,6,0,448
1,2015100002,3.32,2015-01-01,40.110937,-5.727706,1.0,14,10,68,CUACOS DE YUSTE,...,0,1,0,0,130,1510,12,2,0,0
2,2015320001,4.20,2015-01-01,42.366316,-7.325570,1.0,3,32,70,SAN XOAN DE RIO,...,1,1,0,0,135,160,5,1,0,0
3,2015320002,2.24,2015-01-01,41.944387,-7.974655,1.0,3,32,51,MUIÑOS,...,1,1,0,0,185,250,5,1,0,0
4,2015360001,6.88,2015-01-01,42.622507,-8.258003,1.0,3,36,52,SILLEDA,...,1,5,0,0,133,170,6,2,1108,0

In [ ]:
df_wildfire_2018 = df_wildfire.loc[df_wildfire["fecha"].str.contains("2018")]
print(df_wildfire_2018.head())

               id  superficie       fecha        lat       lng  \
11780  2018080002       6.630  2018-01-01  41.273513  1.943018
11781  2018180001       1.226  2018-01-01  36.935828 -3.580621
11782  2018040003       5.240  2018-01-02  36.983515 -1.928601
11783  2018250001       1.080  2018-01-02  41.667752  1.330803
11784  2018330002       3.000  2018-01-02  43.295555 -6.056661

       latlng_explicit  idcomunidad  idprovincia  idmunicipio      municipio  \
11780              1.0            2            8           56  CASTELLDEFELS
11781              1.0            4           18          902      VALLE, EL
11782              1.0            4            4           32     CARBONERAS
11783              1.0            2           25           72        CERVERA
11784              1.0            5           33           26          GRADO

       ...  causa_supuesta  causa_desc  muertos  heridos  time_ctrl  time_ext  \
11780  ...               0          24        0        0        234      1044
11781  ...               0          16        0        0        200      1535
11782  ...               0          12        0        0        322      1500
11783  ...               1          12        0        0         95       287
11784  ...               0           0        0        0          0       216

       personal  medios  gastos  perdidas
11780       116      28       0         0
11781        25       1     341         0
11782        48       3       0         0
11783        23       6       0         0
11784         0       0       0         0

[5 rows x 21 columns]

In [ ]:
"2018"<"2018-01-01"<"2018-12-31"<"2019"<"2019-01-01"  #IMPORTANT

True

In [ ]:
df_wildfire_2018_2 = df_wildfire.set_index("fecha")
df_wildfire_2018_2 = df_wildfire_2018_2.loc["2018-01-01":"2018-12-31"]
print(df_wildfire_2018_2.head(5))

                    id  superficie        lat       lng  latlng_explicit  \
fecha
2018-01-01  2018080002       6.630  41.273513  1.943018              1.0
2018-01-01  2018180001       1.226  36.935828 -3.580621              1.0
2018-01-02  2018040003       5.240  36.983515 -1.928601              1.0
2018-01-02  2018250001       1.080  41.667752  1.330803              1.0
2018-01-02  2018330002       3.000  43.295555 -6.056661              1.0

            idcomunidad  idprovincia  idmunicipio      municipio  causa  \
fecha
2018-01-01            2            8           56  CASTELLDEFELS      3
2018-01-01            4           18          902      VALLE, EL      2
2018-01-02            4            4           32     CARBONERAS      2
2018-01-02            2           25           72        CERVERA      2
2018-01-02            5           33           26          GRADO      5

            causa_supuesta  causa_desc  muertos  heridos  time_ctrl  time_ext  \
fecha
2018-01-01               0          24        0        0        234      1044
2018-01-01               0          16        0        0        200      1535
2018-01-02               0          12        0        0        322      1500
2018-01-02               1          12        0        0         95       287
2018-01-02               0           0        0        0          0       216

            personal  medios  gastos  perdidas
fecha
2018-01-01       116      28       0         0
2018-01-01        25       1     341         0
2018-01-02        48       3       0         0
2018-01-02        23       6       0         0
2018-01-02         0       0       0         0

## Merge & Join

Concatenating DataFrames makes sense for "partitioned" data:
- Identical schema, different rows (`concat`)
- Identical rows, additional columns (`concat(axis="columns")`)

However, many more situations require a smarter way of combining datasets.

The `.merge` method implements SQL `JOIN`-like operations in pandas.

(`.join` is similar to `.merge`, but includes some optimizations when working with indexes)

In [ ]:
import pandas as pd

Use case: we have our big renters data for Madrid, with lots of rich information:

In [ ]:
df_madrid = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/"
    "data/grandes-tenedores-madrid.csv"
)
df_madrid.head()

,NIF,Filial propietaria directa,Inmuebles,Matriz,Sede empresa matriz,Sociedad intermedia utilizada,Sede sociedad utilizada,Tipo sociedad utilizada,Administración,Sector,Subsector,Fuente,Fuente 2,Fuente 3,Fuente 4,Fuente 5,Fuente 6,Fuente 7,Fuente 8
0,A70302039,ABANCA CORPORACION BANCARIA SA,55,Abanca,España,Abanca,España,Empresa privada,NaN,Entidades financieras,Banca,https://civio.box.com/s/66p5k4lv0dr7ox37wzvnlk...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B09658576,"ACEF SPAIN PROPCO, S.L.U.",523,Axa,Francia,Acef Holding S.C.A,Luxemburgo,Socimi,NaN,Seguros,NaN,https://www.boe.es/borme/dias/2022/04/08/pdfs/...,https://www.boe.es/borme/dias/2022/04/07/pdfs/...,https://www.boe.es/borme/dias/2022/05/06/pdfs/...,NaN,NaN,NaN,NaN,NaN
2,B31813843,"ADANIA PATRIMONIO, S.L.",148,Adania,España,Adania,España,Empresa privada,NaN,Inmobiliaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Q2802152E,ADIF-ALTA VELOCIDAD,142,Adif,España,Adif,España,Empresas públicas o administraciones,Administración central,Otros,Infraestructuras aeroportuarias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B83195800,ADMAFINCAS S.L,88,Admafincas SL,España,Admafincas SL,España,Empresa privada,NaN,Inmobiliaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

And we have data for Spain as well, but it's very lacking:

In [ ]:
df_spain = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/"
    "data/megatenedores_estatal_2024.csv"
)
df_spain.head()

                       Matriz                  CCAA     Tipo  viviendas
0              1948 Associats              Cataluña  Privado         58
1  2002 Nuevas Inversiones SL  Comunidad Valenciana  Privado         88
2       2020 Immopedralbel SL              Cataluña  Privado         52
3      A3 Domus Habitatges SL              Cataluña  Privado         55
4                         ACS                Madrid  Privado        112

Would it be possible to _augment_ the Spain data with part of the information coming from the Madrid one?

In [ ]:
df_madrid_company_data = (
    df_madrid.loc[:, ["NIF", "Filial propietaria directa", "Matriz"]]
    .rename(columns={
        "Matriz": "Holding",
        "Filial propietaria directa": "Branch",
    })
)
df_madrid_company_data.head()

In [ ]:
len(df_madrid_company_data)

Both DataFrames have the `Matriz` column ("Holding") in common. However, for each `Matriz`, there is more than one possible value of `Filial` ("Branch"):

In [ ]:
df_madrid_company_data["Holding"].nunique()

In [ ]:
(
    df_madrid_company_data
    .groupby("Holding")["Branch"].size()
    .sort_values()
)

In [ ]:
(
    df_madrid_company_data
    .loc[df_madrid_company_data["Holding"] == "Blackstone"]
    .head()
)

For the purposes of this exercise, let's pretend that `1 Holding = 1 Branch`.

In [ ]:
df_madrid_company_data_simple = (
    df_madrid_company_data.drop_duplicates(subset="Holding")
)
df_madrid_company_data_simple["Branch"].is_unique

Now, combining this data is a matter of calling the `.merge` method appropriatly:

In [ ]:
df_spain_augmented = (
    df_spain
    .merge(
        df_madrid_company_data_simple,
        how="left",  # same as `LEFT JOIN` in SQL
        left_on="Matriz",
        right_on="Holding",
    )
)
df_spain_augmented.head()

Notice that, where there was available data, pandas combined the rows, leaving `NaN` in the rest of the places.

The `.join` method is like the `.merge` one, but it's more efficient when working with indexes.

In [ ]:
df_madrid_company_data_simple.head(1)

In [ ]:
df_spain.head(1)

In [ ]:
df_spain.set_index("Matriz").head(1)

In [ ]:
(
    df_spain.set_index("Matriz")
    .join(
        df_madrid_company_data_simple.set_index("Holding")
    )
    .head()
)

## Exercises

### 2. European Commission lobbists

Below you can find some data coming from Civio on lobby meetings at the European Commission.

In [1]:
LOBBY_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/commission-lobbists-meetings.csv"
)

However, we know very little about the "lobbyst". Below, you can find some extra information (AI-generated) on some of them.

In [2]:
LOBBY_DATA_AI_GEN_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/"
    "lobby_data_ai.csv"
)

In [3]:
import pandas as pd
df_lobby = pd.read_csv(LOBBY_DATA_URL)
df_lobby_AI = pd.read_csv(LOBBY_DATA_AI_GEN_URL)

In [6]:
df_lobby.head(5)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,nr,commission_representative,portfolio,date,location,subject(s)-edited,lobbyist,health_meeting_or_lab,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,"Ladislav Miko, Director-General",Director-General of Health and Food Safety (SA...,15/04/2015,"Brussels, BELGIUM",Seeds,"ARCHE NOAH, Gesellschaft für die Erhaltung der...",False,NaN,NaN,NaN
1,2,"Arunas Ribokas, Cabinet member of Vytenis Andr...",Health & Food Safety,30/01/2015,Brussels,"The Food Chain, Innovation and Challenges, Foo...","ARCHE NOAH, Gesellschaft für die Erhaltung der...",False,NaN,NaN,NaN
2,3,"Nathalie Chaze, Cabinet member of Vytenis Andr...",Health & Food Safety,6/01/2015,Brussels,Plant Reproductive Material Proposal,"ARCHE NOAH, Gesellschaft für die Erhaltung der...",False,NaN,NaN,NaN
3,1,"Roberto Viola, Director-General","Director-General of Communications Networks, C...",21/02/2019,Brussels,Quantum Technologies,Austrian Institute of Technology GmbH (AIT),False,NaN,NaN,NaN
4,2,"Mariya Gabriel, Commissioner",Digital Economy and Society,8/01/2019,Sofia,"Cloud computing, Cybersecurity",Austrian Institute of Technology GmbH (AIT),False,NaN,NaN,NaN

In [8]:
df_lobby['lobbyist'].value_counts()

lobbyist
Google                                                                                                         250
Bureau Européen des Unions de Consommateurs (BEUC)                                                             189
Transport and Environment (European Federation for Transport and Environment) (T&E)                            155
WWF European Policy Programme (WWF EPO)                                                                        151
DIGITALEUROPE (DE)                                                                                             151
                                                                                                              ...
International Association of Ports and Harbors (IAPH)                                                            1
VAS-European Independent Foundation in Angiology-Vascular Medicine (VAS)                                         1
Università Cattolica del Sacro Cuore (UCSC)                                                                      1
TRIUMPH GROUP INTERNATIONAL (TGI)                                                                                1
Regione Toscana - Ufficio di collegamento con le Istituzioni comunitarie a Bruxelles (Regione Toscana Brux)      1
Name: count, Length: 1398, dtype: int64

In [5]:
df_lobby_AI.head()

,Entity,Policy Orientation,Geographic Origin,EU Constituency Role
0,Google,Digital & Technology Policy,US,Business / Industry Representatives
1,Bureau Européen des Unions de Consommateurs (B...,Social & Environmental Policy,EU,Public Interest Advocacy
2,Transport and Environment (T&E),Social & Environmental Policy,EU,Public Interest Advocacy
3,DIGITALEUROPE (DE),Digital & Technology Policy,EU,Industry Representatives
4,WWF European Policy Programme (WWF EPO),Social & Environmental Policy,International,Public Interest Advocacy

In [11]:
df_ALL = df_lobby.merge(df_lobby_AI,
                        how = 'left',
                        left_on='lobbyist',
                        right_on='Entity')

In [10]:
df_ALL.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,nr,commission_representative,portfolio,date,location,subject(s)-edited,lobbyist,health_meeting_or_lab,Unnamed: 8,Unnamed: 9,Unnamed: 10,Entity,Policy Orientation,Geographic Origin,EU Constituency Role
0,1.0,"Diederik Samsom, Cabinet member of Frans Timme...",European Green Deal,8/12/2020,videoconference (Brussels),Online discussion with #SustainablePublicAffai...,#SustainablePublicAffairs (#Sustainable),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,"Jori Keijsper, Cabinet member of Frans Timmermans",European Green Deal,27/11/2020,Brussels - video conference,Introduction to Sustainable Public Affairs,#SustainablePublicAffairs (#Sustainable),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,"Chris Uregian, Cabinet member of Margaritis Sc...",Promoting the European Way of Life,13/05/2020,Virtual meeting,Tourism package,(SETE) GREEK TOURISM CONFEDERATION (SETE),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,"Raquel Lucas, Cabinet member of Valdis Dombrov...","Euro and Social Dialogue, also in charge of Fi...",21/02/2018,Brussels,"state of play of Greece programme, economic gr...",(SETE) GREEK TOURISM CONFEDERATION (SETE),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,"Justyna Morek, Cabinet member of Elżbieta Bień...","Internal Market, Industry, Entrepreneurship an...",21/02/2018,BRUSSELS,Exchange of views on current topics,(SETE) GREEK TOURISM CONFEDERATION (SETE),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Combine both datasets to answer these questions:

- What are the top 10 lobbysts in terms of number of meetings?
- How many meetings happened with US vs with EU-based lobbysts?
- What was the most common policy orientation of the meetings?
- Now, answer the same questions, but using only meetings with a "high" number of representatives (let's use `nr > mean(nr)`)

In [16]:
df_ALL.groupby('lobbyist').size().sort_values(ascending=False).head(10)

lobbyist
Google                                                                                 250
Bureau Européen des Unions de Consommateurs (BEUC)                                     189
Transport and Environment (European Federation for Transport and Environment) (T&E)    155
WWF European Policy Programme (WWF EPO)                                                151
DIGITALEUROPE (DE)                                                                     151
American Chamber of Commerce to the European Union (AmCham EU)                         144
Microsoft Corporation                                                                  144
EuroCommerce                                                                           138
European farmers (COPA)                                                                137
Vodafone Belgium SA (VBSA)                                                             123
dtype: int64

In [14]:
df_ALL['Geographic Origin'].value_counts()

Geographic Origin
EU               1419
International     461
US                458
Name: count, dtype: int64

In [15]:
df_ALL['Policy Orientation'].value_counts()

Policy Orientation
Digital & Technology Policy          607
Social & Environmental Policy        591
Business & Industry Policy           487
Telecommunications & Connectivity    300
Agriculture & Food Policy            252
Economic & Financial Policy          101
Name: count, dtype: int64

In [17]:
mean_nr = df_ALL['nr'].mean()
df_ALL.loc[df_ALL['nr'] > mean_nr].head(2)

,nr,commission_representative,portfolio,date,location,subject(s)-edited,lobbyist,health_meeting_or_lab,Unnamed: 8,Unnamed: 9,Unnamed: 10,Entity,Policy Orientation,Geographic Origin,EU Constituency Role
88,25,"Emma Udwin, Cabinet member of Johannes Hahn",European Neighbourhood Policy & Enlargement Ne...,2/03/2017,Brussels,Natura 2000,Wirtschaftskammer Österreich (WKÖ),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,26,"Michael Karnitschnig, Cabinet member of Johann...",European Neighbourhood Policy & Enlargement Ne...,2/02/2017,Brussels,Economic policy issues,Wirtschaftskammer Österreich (WKÖ),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
float('nan') == float('nan')

False

## Dealing with missing data

As you have noticed already, lots of pandas operations generate missing data in the form of `NaN`.

Filtering this data with the usual methods doesn't work, because, following the IEEE 754 standard, NaN is different from itself:

In [ ]:
float("nan") == float("nan")

pandas DataFrames have special methods to deal with missing data:

In [ ]:
df_spain_augmented.head()

Filter:

In [ ]:
df_spain_augmented.loc[
    df_spain_augmented["NIF"].isna()
].head()

Dropping rows with missing data:

In [ ]:
df_spain_augmented.dropna(subset="NIF").head()

Filling missing data:

In [ ]:
df_spain_augmented.fillna({"NIF": "<UNKNOWN>"}).head()

## Exercises

### 3. Missing location and puzzling columns

- Observe that, in the European Commission dataset, the `location` column is sometimes null. Inspect how many rows have this property. What would you do with those? (Open question)
- There are some trailing columns in the dataset with some null values. How many non-null values do they have? What would you do with those? (Open question with a "more correct" answer)