# Homework 1: Polars Basics

In this homework, you'll practice the Polars fundamentals we learned in Session 1.

## Dataset: Spotify Tracks

You'll work with a dataset of Spotify tracks containing information about songs, artists, and audio features.

## Instructions

- Complete each exercise in the provided code cells
- Expected outputs are shown after each exercise
- Use the Polars expression API (`pl.col()`, `select()`, `with_columns()`, etc.)

In [2]:
import polars as pl

## Exercise 1: Load the Data (10 points)

Load the `spotify_tracks.csv` file into a Polars DataFrame called `tracks`.

In [3]:
# Your code here
tracks = pl.read_csv("https://raw.githubusercontent.com/Navenkumar-Balasubramaniam/00-General/refs/heads/main/18%20Polars/spotify_tracks.csv")

tracks.head()

shape: (5, 12)
┌──────────┬──────────────┬──────────────┬──────────┬───┬────────┬───────┬──────────────┬──────────┐
│ track_id ┆ track_name   ┆ artist       ┆ album    ┆ … ┆ energy ┆ tempo ┆ release_date ┆ streams  │
│ ---      ┆ ---          ┆ ---          ┆ ---      ┆   ┆ ---    ┆ ---   ┆ ---          ┆ ---      │
│ str      ┆ str          ┆ str          ┆ str      ┆   ┆ f64    ┆ f64   ┆ str          ┆ i64      │
╞══════════╪══════════════╪══════════════╪══════════╪═══╪════════╪═══════╪══════════════╪══════════╡
│ TRK00001 ┆ Neon Stars   ┆ Taylor Swift ┆ Album 27 ┆ … ┆ 0.444  ┆ 171.1 ┆ 2023-01-19   ┆ 18342071 │
│ TRK00002 ┆ Bright       ┆ Ed Sheeran   ┆ Album 33 ┆ … ┆ 0.889  ┆ 106.1 ┆ 2024-07-16   ┆ 264598   │
│          ┆ Dreams       ┆              ┆          ┆   ┆        ┆       ┆              ┆          │
│ TRK00003 ┆ Lost Nights  ┆ Drake        ┆ Album 29 ┆ … ┆ 0.031  ┆ 173.6 ┆ 2016-09-09   ┆ 30375584 │
│ TRK00004 ┆ Dark Dreams  ┆ Maroon 5     ┆ Album 46 ┆ … ┆ 0.126  ┆ 115.8 ┆ 2018-01-30   ┆ 47107386 │
│ TRK00005 ┆ Wild Echoes  ┆ BTS          ┆ Album 31 ┆ … ┆ 0.046  ┆ 193.8 ┆ 2022-01-27   ┆ 3181786  │
└──────────┴──────────────┴──────────────┴──────────┴───┴────────┴───────┴──────────────┴──────────┘

## Exercise 2: Inspect the Data (10 points)

Answer the following questions:
1. How many rows and columns are in the dataset?
2. What are the column names?
3. What are the data types of each column?

In [4]:
# 2.1 Number of rows and columns
tracks.height, tracks.width

(5000, 12)

In [5]:
# 2.2 Column names
tracks.columns

['track_id',
 'track_name',
 'artist',
 'album',
 'genre',
 'duration_ms',
 'popularity',
 'danceability',
 'energy',
 'tempo',
 'release_date',
 'streams']

In [6]:
# 2.3 Data types (schema)
tracks.schema

Schema([('track_id', String),
        ('track_name', String),
        ('artist', String),
        ('album', String),
        ('genre', String),
        ('duration_ms', Int64),
        ('popularity', Int64),
        ('danceability', Float64),
        ('energy', Float64),
        ('tempo', Float64),
        ('release_date', String),
        ('streams', Int64)])

## Exercise 3: Select Columns (15 points)

Create a new DataFrame with only the following columns:
- `track_name`
- `artist`
- `genre`
- `popularity`

Store it in a variable called `tracks_basic`.

In [7]:
# Your code here
tracks_basic = tracks.select(pl.col("track_name"),pl.col("artist"),pl.col("genre"),pl.col("popularity"))

# Show first 5 rows
tracks_basic.head()

shape: (5, 4)
┌───────────────┬──────────────┬───────┬────────────┐
│ track_name    ┆ artist       ┆ genre ┆ popularity │
│ ---           ┆ ---          ┆ ---   ┆ ---        │
│ str           ┆ str          ┆ str   ┆ i64        │
╞═══════════════╪══════════════╪═══════╪════════════╡
│ Neon Stars    ┆ Taylor Swift ┆ Rock  ┆ 23         │
│ Bright Dreams ┆ Ed Sheeran   ┆ Indie ┆ 28         │
│ Lost Nights   ┆ Drake        ┆ Indie ┆ 84         │
│ Dark Dreams   ┆ Maroon 5     ┆ Pop   ┆ 65         │
│ Wild Echoes   ┆ BTS          ┆ Latin ┆ 67         │
└───────────────┴──────────────┴───────┴────────────┘

## Exercise 4: Create New Columns (20 points)

Using `with_columns()`, add the following columns to the `tracks` DataFrame:

1. `duration_min`: Duration in minutes (convert `duration_ms` to minutes by dividing by 60000)
2. `streams_millions`: Streams in millions (divide `streams` by 1,000,000)
3. `track_name_upper`: Track name in uppercase

Store the result in `tracks_enhanced`.

In [9]:
# Your code here
tracks_enhanced = tracks.with_columns(
    (pl.col("duration_ms")/60000).alias("duration_min"),
     (pl.col("streams")/1000000).alias("streams_millions"),
    (pl.col("track_name").str.to_uppercase()).alias("track_name_upper")
)

# Show relevant columns
tracks_enhanced.select(
    "track_name", "duration_ms", "duration_min",
    "streams", "streams_millions", "track_name_upper"
).head()

shape: (5, 6)
┌───────────────┬─────────────┬──────────────┬──────────┬──────────────────┬──────────────────┐
│ track_name    ┆ duration_ms ┆ duration_min ┆ streams  ┆ streams_millions ┆ track_name_upper │
│ ---           ┆ ---         ┆ ---          ┆ ---      ┆ ---              ┆ ---              │
│ str           ┆ i64         ┆ f64          ┆ i64      ┆ f64              ┆ str              │
╞═══════════════╪═════════════╪══════════════╪══════════╪══════════════════╪══════════════════╡
│ Neon Stars    ┆ 195719      ┆ 3.261983     ┆ 18342071 ┆ 18.342071        ┆ NEON STARS       │
│ Bright Dreams ┆ 212121      ┆ 3.53535      ┆ 264598   ┆ 0.264598         ┆ BRIGHT DREAMS    │
│ Lost Nights   ┆ 153200      ┆ 2.553333     ┆ 30375584 ┆ 30.375584        ┆ LOST NIGHTS      │
│ Dark Dreams   ┆ 152600      ┆ 2.543333     ┆ 47107386 ┆ 47.107386        ┆ DARK DREAMS      │
│ Wild Echoes   ┆ 310592      ┆ 5.176533     ┆ 3181786  ┆ 3.181786         ┆ WILD ECHOES      │
└───────────────┴─────────────┴──────────────┴──────────┴──────────────────┴──────────────────┘

## Exercise 5: Aggregations (20 points)

Calculate the following statistics for the `tracks` DataFrame in a single `select()` statement:

1. Average popularity (`avg_popularity`)
2. Maximum streams (`max_streams`)
3. Minimum tempo (`min_tempo`)
4. Number of unique artists (`unique_artists`)
5. Total number of tracks (`total_tracks`)

In [10]:
# Your code here
stats = tracks.select(
    pl.col("popularity").mean().alias("avg_popularity"),
    pl.col("streams").max().alias("max_streams"),
    pl.col("tempo").min().alias("min_tempo"),
    pl.col("artist").n_unique().alias("unique_artists"),
    pl.col("track_name").count().alias("total_tracks")
)
stats

shape: (1, 5)
┌────────────────┬─────────────┬───────────┬────────────────┬──────────────┐
│ avg_popularity ┆ max_streams ┆ min_tempo ┆ unique_artists ┆ total_tracks │
│ ---            ┆ ---         ┆ ---       ┆ ---            ┆ ---          │
│ f64            ┆ i64         ┆ f64       ┆ u32            ┆ u32          │
╞════════════════╪═════════════╪═══════════╪════════════════╪══════════════╡
│ 49.0076        ┆ 49993563    ┆ 60.0      ┆ 20             ┆ 5000         │
└────────────────┴─────────────┴───────────┴────────────────┴──────────────┘

## Exercise 6: Select by Data Type (10 points)

Create a DataFrame containing only the numeric columns (Int64 and Float64) from `tracks`.

In [11]:
# Your code here
numeric_cols = tracks.select(pl.col(pl.NUMERIC_DTYPES))
numeric_cols.head()

/tmp/ipython-input-416/196071147.py:2: DeprecationWarning: `NUMERIC_DTYPES` was deprecated in version 1.0.0. Define your own data type groups or use the `polars.selectors` module for selecting columns of a certain data type.
  numeric_cols = tracks.select(pl.col(pl.NUMERIC_DTYPES))

shape: (5, 6)
┌─────────────┬────────────┬──────────────┬────────┬───────┬──────────┐
│ duration_ms ┆ popularity ┆ danceability ┆ energy ┆ tempo ┆ streams  │
│ ---         ┆ ---        ┆ ---          ┆ ---    ┆ ---   ┆ ---      │
│ i64         ┆ i64        ┆ f64          ┆ f64    ┆ f64   ┆ i64      │
╞═════════════╪════════════╪══════════════╪════════╪═══════╪══════════╡
│ 195719      ┆ 23         ┆ 0.006        ┆ 0.444  ┆ 171.1 ┆ 18342071 │
│ 212121      ┆ 28         ┆ 0.903        ┆ 0.889  ┆ 106.1 ┆ 264598   │
│ 153200      ┆ 84         ┆ 0.561        ┆ 0.031  ┆ 173.6 ┆ 30375584 │
│ 152600      ┆ 65         ┆ 0.161        ┆ 0.126  ┆ 115.8 ┆ 47107386 │
│ 310592      ┆ 67         ┆ 0.645        ┆ 0.046  ┆ 193.8 ┆ 3181786  │
└─────────────┴────────────┴──────────────┴────────┴───────┴──────────┘

## Exercise 7: Save to Parquet (15 points)

1. Save the `tracks_enhanced` DataFrame to a Parquet file called `tracks_enhanced.parquet`
2. Read it back into a new DataFrame called `tracks_from_parquet`
3. Verify the shape matches the original

In [12]:
# 7.1 Save to Parquet
tracks_enhanced.write_parquet("tracks_enhanced.parquet")

In [13]:
# 7.2 Read back from Parquet
tracks_from_parquet = pl.read_parquet("tracks_enhanced.parquet")

In [14]:
# 7.3 Verify shapes match
print(f"Original shape: {tracks_enhanced.shape}")
print(f"From Parquet shape: {tracks_from_parquet.shape}")
print(f"Shapes match: {tracks_enhanced.shape == tracks_from_parquet.shape}")

Original shape: (5000, 15)
From Parquet shape: (5000, 15)
Shapes match: True

## Bonus Exercise: Complex Expression (10 bonus points)

Create a new column called `energy_category` based on the `energy` value:
- If energy >= 0.8: "High Energy"
- If energy >= 0.5: "Medium Energy"
- Otherwise: "Low Energy"

Hint: You'll need to use `pl.when().then().otherwise()` which we'll cover in detail in Session 2, but try to figure it out!

In [18]:
# Bonus: Your code here
tracks_with_category = tracks.with_columns(
    (pl.when(pl.col("energy") >= 0.8).then(pl.lit("High Energy"))
    .when(pl.col("energy") >= 0.5).then(pl.lit("Medium Energy")).otherwise(pl.lit("Low Energy"))).alias("energy_category")
)

# Show sample results
tracks_with_category.select("track_name", "energy", "energy_category").head(10)

shape: (10, 3)
┌─────────────────┬────────┬─────────────────┐
│ track_name      ┆ energy ┆ energy_category │
│ ---             ┆ ---    ┆ ---             │
│ str             ┆ f64    ┆ str             │
╞═════════════════╪════════╪═════════════════╡
│ Neon Stars      ┆ 0.444  ┆ Low Energy      │
│ Bright Dreams   ┆ 0.889  ┆ High Energy     │
│ Lost Nights     ┆ 0.031  ┆ Low Energy      │
│ Dark Dreams     ┆ 0.126  ┆ Low Energy      │
│ Wild Echoes     ┆ 0.046  ┆ Low Energy      │
│ Midnight Stars  ┆ 0.827  ┆ High Energy     │
│ Silent Hearts   ┆ 0.45   ┆ Low Energy      │
│ Endless Dreams  ┆ 0.427  ┆ Low Energy      │
│ Electric Hearts ┆ 0.092  ┆ Low Energy      │
│ Lost Dreams     ┆ 0.034  ┆ Low Energy      │
└─────────────────┴────────┴─────────────────┘